### ISSUE TITLE
Static manual pages not generated

### ISSUE THREAD

**Issue by hashkeeperok** [1200wd/bitcoinlib#144]
http://bitcoinlib.readthedocs.io/en/latest/_static/manuals.databases.html  - this url don't working

**Comment by mccwdev** [comment]
Thanks for pointing that out, for some reason Sphinx didn't generate the static pages. I will fix it later, but you can find the database manual below.

--

Using MySQL or PostgreSQL databases
Bitcoinlib uses the SQLite database by default, because it easy to use and requires no installation.

But you can also use other databases. At this moment Bitcoinlib is tested with MySQL and PostgreSQL.

Using MySQL database
We assume you have a MySQL server at localhost. Unlike with the SQLite database MySQL databases are not created automatically, so create one from the mysql command prompt:

mysql> create database bitcoinlib;
Now create a user for your application and grant this user access. And off course replace the password 'secret' with a better password.

mysql> create user bitcoinlib@localhost identified by 'secret';
mysql> grant all on bitcoinlib.* to bitcoinlib@localhost with grant option;
In your application you can create a database link. The database tables are created when you first run the application

db_uri = 'mysql://bitcoinlib:secret@localhost:3306/bitcoinlib'
w = wallet_create_or_open('wallet_mysql', db_uri=db_uri)
w.info()
Using PostgreSQL database
First create a user and the database from a shell. We assume you have a PostgreSQL server running at your Linux machine.

$ su - postgres
postgres@localhost:~$ createuser --interactive --pwprompt
Enter name of role to add: bitcoinlib
Enter password for new role:
Enter it again:
Shall the new role be a superuser? (y/n) n
Shall the new role be allowed to create databases? (y/n) n
Shall the new role be allowed to create more new roles? (y/n) n
$ createdb bitcoinlib
And assume you unwisely have chosen the password 'secret' you can use the database as follows:

db_uri = 'postgresql://bitcoinlib:secret@localhost:5432/'
w = wallet_create_or_open('wallet_mysql', db_uri=db_uri)
w.info()

**Comment by mccwdev** [comment]
Fixed in latest version: https://bitcoinlib.readthedocs.io/en/master/
