### ISSUE TITLE
Several errors linked to HDWallet while using bitcoind-testnet

### ISSUE THREAD

**Issue by guang2013** [1200wd/bitcoinlib#99]
1. I created several HDWallet and tried to use the scan() method, but it gives errors saying that the gettransactions method does not exist in BitcoindClient. 
2. I don't know how to link the bitcoinlib wallet to bitcoind wallet. As I used the address from HDWallet and made a call getaddressinfo, but found that attributes in the response ( like ismine and iswatchonly) are false. It is located in getutxos line 183. 

3. How do I make the HDWallet address in the bitcoind wallet? Or how do I load HDWallet created from bitcoinlib to bitcoind network?

4. When I send bitcoin through HDWallet.send_to(), it always fails and said that it could not get utxos. 
5. When I run utxos_update, it always failed and the reason is that the wallet I used is not linked to bitcoind wallet. 

Could anybody help with this? Much appreciated.

**Comment by Moliholy** [comment]
1. Yes, there is no `gettransactions` method. I solved it by manually generating as many addresses as I required and once they are in the database I refresh the utxos via the `utxos_update` method.

2. That has already been discussed in https://github.com/1200wd/bitcoinlib/issues/94. I proposed a solution in that issue, but essentially you have to manually interact with your bitcoind node via RPC.

3. It's also explained in the previous issue, but essentially you must manually use the [importaddress](https://chainquery.com/bitcoin-cli/importaddress) method.

4. Are you sure you have enough funds? And if you believe you do, did you refresh the UTXOs before sending?

5. As I mentioned, you have to code a custom mechanism by yourself so that those addresses are included in the bitcoind wallet.

Also, if you do not control the bitcoind node, you simply can't use it with this library in its current state. And anyway, to be honest there are better options for this matter. I believe in the master branch it's been recently added the [bcoin](https://bcoin.io/) provider, which if configured properly can index both transactions and addresses. I personally plan to stop using bitcoind to start using this node.
